In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3,4,5,'a'])
a

array(['1', '2', '3', '4', '5', 'a'], dtype='<U21')

In [5]:
print(a)

['1' '2' '3' '4' '5' 'a']


In [6]:
#define a,b,c and d as instructed above

a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7,8,9], [10,11,12]]])

In [7]:
#print dimentions of a,b, c and d
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [8]:
# print shape of each a,b ,c and d
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)


()
(3,)
(2, 3)
(2, 2, 3)


In [9]:
print(c.dtype)

int64


In [10]:
print(type(c))

<class 'numpy.ndarray'>


In [11]:
print(len(c))

2


In [19]:
# Creating a Numpy Arrays
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [21]:
np.eye(2, dtype = float) 

array([[1., 0.],
       [0., 1.]])

In [22]:
np.zeros((3, 3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [16]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
np.full((2, 3), 10,dtype=int)

array([[10, 10, 10],
       [10, 10, 10]])

In [24]:
x = [1,2,3,4]
np.diag(x)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [27]:
#Reshape

x = np.arange(1, 26)
print(x)

n=x.reshape((5,5)) # 1d
print(n)
print(n.shape)
print(n.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
(5, 5)
2


In [28]:
#Ravel
# convert to old dimension

v=n.ravel()
print(v.shape)
print(v)
print(v.ndim)

(25,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
1


In [30]:
#converts into 1D Array

x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [31]:
x1= np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# assign x2 = x1
x2 = x1 # view 

print(x1)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [33]:
# change 1st element of x2 as 10
x2[0] = 10

#Again print x1 and x2
print(x1)
print(x2)


print(id(x1))
print(id(x2))


# Check memory share between x1 and x2
print(np.shares_memory(x1, x2))
print(id(x1))
print(id(x2))

[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]
1881336149264
1881336149264
True
1881336149264
1881336149264


In [34]:
# Create a view of x1 and store it in x3.
x3 = x1.view()

# Again check memory share between x1 and x3
np.shares_memory(x1, x3)

#Change 1st element of x3=100
x3[0] = 100


#print x1 and x3 to check if changes reflected in both
print(x1)
print(x3)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


In [35]:
# Now create an array x4 which is copy of x1
x4 = np.copy(x1)

# Change the last element of x4 as 900
x4[-1] = 900

# print both x1 and x4 to check if changes reflected in both
print(x1)
print(x4)

#Check memory share between x1 and x4
print(id(x1))
print(id(x4))
np.shares_memory(x1, x4)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]
1881336149264
1881350513424


False

In [46]:
z=np.arange(1,17)
print(z)

z1=z.reshape((4,4))


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [47]:

# Print Transpose of array 'a'
print(z1.transpose())
print("-----------------")
print(z1) 


[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
-----------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [48]:
# stack x1 and x4 along columns.
print(x1)
print(x4)
np.vstack((x1, x4))

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [100,   1,   2,   3,   4,   5,   6,   7,   8, 900]])

In [49]:
# delete 2nd element from array x2
print(x2)
np.delete(x2, 0)

[100   1   2   3   4   5   6   7   8   9]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# print the indexes where the value is 4 in array x1

m=np.where(x1 == 4)
m

(array([4]),)

In [51]:
# Print x1 where x1 is greater than 5, also if number is less than 5 then replace it with 0

np.where(x1>5, x1, 0)

array([100,   0,   0,   0,   0,   0,   6,   7,   8,   9])